import jsPDF from "jspdf";
import type { NutritionInfo } from "@/data/nutritionData";
import { healthScore } from "./nutritionUtils";

export function exportNutritionPDF(n: NutritionInfo) {
  const doc = new jsPDF();
  const score = healthScore(n);

  doc.setFontSize(22);
  doc.setTextColor(40, 130, 80);
  doc.text("NutriScan Pro — Nutrition Report", 14, 20);

  doc.setDrawColor(40, 130, 80);
  doc.line(14, 24, 196, 24);

  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text(`${n.emoji ?? ""} ${n.name}`, 14, 36);

  doc.setFontSize(11);
  doc.setTextColor(80, 80, 80);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 43);
  if (n.servingLabel) doc.text(`Serving: ${n.servingLabel}`, 14, 49);

  const rows: [string, string][] = [
    ["Calories", `${n.calories} kcal`],
    ["Protein", `${n.protein} g`],
    ["Carbohydrates", `${n.carbs} g`],
    ["Total Fat", `${n.fat} g`],
    ["Good Fat", `${n.goodFat} g`],
    ["Bad Fat", `${n.badFat} g`],
  ];
  if (n.fiber !== undefined) rows.push(["Fiber", `${n.fiber} g`]);
  if (n.sugar !== undefined) rows.push(["Sugar", `${n.sugar} g`]);
  if (n.sodium !== undefined) rows.push(["Sodium", `${n.sodium} mg`]);

  let y = 56;
  doc.setFontSize(13);
  doc.setTextColor(20, 20, 20);
  doc.text("Nutrition Breakdown", 14, y);
  y += 6;
  doc.setFontSize(11);
  rows.forEach(([k, v]) => {
    doc.setTextColor(60, 60, 60);
    doc.text(k, 18, y);
    doc.setTextColor(0, 0, 0);
    doc.text(v, 100, y);
    y += 7;
  });

  y += 4;
  doc.setFontSize(13);
  doc.text("Health Score", 14, y);
  y += 7;
  doc.setFontSize(20);
  doc.setTextColor(40, 130, 80);
  doc.text(`${score.score} / 100 — ${score.label}`, 18, y);

  y += 12;
  doc.setFontSize(13);
  doc.setTextColor(20, 20, 20);
  doc.text("Vitamins", 14, y);
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  doc.text(n.vitamins.join(", ") || "—", 50, y);

  y += 7;
  doc.setFontSize(13);
  doc.setTextColor(20, 20, 20);
  doc.text("Minerals", 14, y);
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  doc.text(n.minerals.join(", ") || "—", 50, y);

  y += 12;
  doc.setFontSize(13);
  doc.setTextColor(20, 20, 20);
  doc.text("Health Tip", 14, y);
  y += 6;
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  const lines = doc.splitTextToSize(n.healthTip, 180);
  doc.text(lines, 14, y);

  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text("Generated by NutriScan Pro · Healthy eating starts with awareness.", 14, 285);

  doc.save(`NutriScan-${n.name.replace(/\s+/g, "_")}.pdf`);
}
